### ISSUE TITLE
[Feature request] Add icon for Runner

### ISSUE THREAD

**Issue by mamadaevv** [PEZ/SketchSeparateShapes#1]
![separate 96](https://user-images.githubusercontent.com/4017693/35664627-f37e10ea-0733-11e8-8282-132af8b8e62a.png)

**Comment by mamadaevv** [comment]
This is icon in format tiff:
[Separate 48.tiff.zip](https://github.com/PEZ/SketchSeparateShapes/files/1684439/Separate.48.tiff.zip)

Please try it too. I think this icon should be more better then png on retina display.

**Comment by PEZ** [comment]
The Runner docs says to use icons that are 64x64. Can you fix, @Mikola35?

**Comment by mamadaevv** [comment]
![separate_64](https://user-images.githubusercontent.com/4017693/35778424-1c29df86-09cf-11e8-8471-a457fc8d9001.png)

**Comment by PEZ** [comment]
This should be fixed now.

**Comment by mamadaevv** [comment]
Looks Great!!!

<img width="469" alt="workspace sketch 2018-02-05 13-23-05" src="https://user-images.githubusercontent.com/4017693/35799767-e3632cbc-0a77-11e8-9571-33c67447b73b.png">
