### ISSUE TITLE
Sketch Version 50 compatibility

### ISSUE THREAD

**Issue by DaniloDesigner** [PEZ/SketchSeparateShapes#12]
Hi.

I just updated Sketch to the version 50 and SketchSeparateShapes stopped working.

I just wanted to let you know and also thank you for this amazing plugin.

Regards,

Dani

**Comment by PEZ** [comment]
Ah, wow. Thanks for the heads up. I’ll have a check.

**Comment by PEZ** [comment]
New version out. It is incompatible with anything less than Sketch 50, but I guess there is only one path forward. :smile:

**Comment by DaniloDesigner** [comment]
Whoah, that was fast!

Thanks a lot for the ultra speed!

Best regards!
