### ISSUE TITLE
Incompatible with Sketch 50.2

### ISSUE THREAD

**Issue by Guito1986** [PEZ/SketchSeparateShapes#13]
Just to let you know that your plugins don't work with latest version of Sketch, no stress.

**Comment by PEZ** [comment]
What, again? I'll have a look and let's hope it is quick to fix this time as well!

Which version of the plugin are you using?

**Comment by PEZ** [comment]
I just tried it and it seems to work for the things I tried. Do you have a test case describing the problem in some more detail?

**Comment by Guito1986** [comment]
I've got Sketch 50.2 and 1.2.4 and it seems to work finally. My bad.

**Comment by PEZ** [comment]
Great! I am happy it works. And glad you alerted me when you thought it didn’t.
