### ISSUE TITLE
can't be used.. 

### ISSUE THREAD

**Issue by namthko** [PEZ/SketchSeparateShapes#14]
Separate Shape isn't working at the sketch 52 any longer.

**Comment by PEZ** [comment]
You are right. The Sketch ”API” seems to have changed. Let's hope I can fix it!

Thanks for the heads up!

**Comment by PEZ** [comment]
I still have no solution but have asked for help again: https://sketchplugins.com/d/1007-sketch-52-msshapegroup-shapewithbezierpath-is-not-a-function/5

**Comment by PEZ** [comment]
Now should work. (With some regression, unfortunatelly. Separate issue about that on its way.)
