### ISSUE TITLE
can not work in the latest sketch version

### ISSUE THREAD

**Issue by Irina1221** [PEZ/SketchSeparateShapes#15]
sorry, this plugin can not work in the latest sketch version ,any update for it?

**Comment by PEZ** [comment]
Yes, I'm sorry. I don't know how to fix it yet, but you reminded me to ask for help again: https://sketchplugins.com/d/1007-sketch-52-msshapegroup-shapewithbezierpath-is-not-a-function/5

**Comment by cjke** [comment]
I've just nudged the bloke that was helping in that thread. Hoping to get some traction.

**Comment by cjke** [comment]
It looks like they have put through an update. I've not worked with Sketch plugins before (though I do have JS experience) - how are you doing with capacity? I might be able to look at this in a week or two? I just need to get my head around the code base first

**Comment by PEZ** [comment]
Thanks, @cjke . I'm looking at it again. I think I got most of the functionality back in place again. Let's see if I remember how to publish updates. :smile:

It would be awesome if you had a look at the code. I don't have much time at all maintaining this little plugin. Using an internal ”API” like this really is quite painful.

**Comment by PEZ** [comment]
Now published a new version. Hoping it will not be too much different from the previous one (when it worked).

**Comment by cjke** [comment]
1.2.6 works almost flawlessly! That was quick!!
The only thing I noticed (and this may have been true for the older one) was that if a shape is fully overlapped it doesn't cut it out of the base shape (it needs to be only partially overlapped to actually seperate it)

**Comment by cjke** [comment]
**Full overlap (doesn't work correctly)**
Before
![image](https://user-images.githubusercontent.com/884065/54961237-04845600-4fb4-11e9-966f-7cef77df2fc4.png)

After
![image](https://user-images.githubusercontent.com/884065/54961257-18c85300-4fb4-11e9-95cf-8420a0b90671.png)

**Partial overlap (does work correctly)**
Before
![image](https://user-images.githubusercontent.com/884065/54961283-2a115f80-4fb4-11e9-80f6-222137eeefb0.png)

After
![image](https://user-images.githubusercontent.com/884065/54961303-38f81200-4fb4-11e9-84d6-716a7389c5fe.png)

**Comment by PEZ** [comment]
Thanks. This used to work. Can you post it as a separate issue? I'd do it myself, but am out of time (and you have access to the markdown for your nice repro. :smile:) 

Closing this for now, as the major breakage is fixed.

**Comment by cjke** [comment]
Absolutely - will do. 
Awesome work on fixing it so quickly, and as you said, it covers the major issue

**Comment by PEZ** [comment]
Well, quickly, I wouldn't say, this has been broken for all too long... Very good with your help in in discovering that silly `.layers()` that I was somehow missing. I needed that help!

**Comment by PEZ** [comment]
OK, so I think I have fixed the full overlap problem now. Please give v1.2.7 a spin.

**Comment by cjke** [comment]
Indeed you have! Awesome mate, great stuff!!
