### ISSUE TITLE
[Feature request] Add button to toolbar

### ISSUE THREAD

**Issue by mamadaevv** [PEZ/SketchSeparateShapes#2]
![image](https://user-images.githubusercontent.com/4017693/35664809-960ca7fe-0734-11e8-873d-98ca907959e4.png)

**Comment by mamadaevv** [comment]
![runner btn in toolbar](https://user-images.githubusercontent.com/4017693/35664964-29b1a572-0735-11e8-8488-1e93251790f8.gif)

Maybe, Runner plugin code can help with this.

**Comment by PEZ** [comment]
Right. Runner proves it is possible to do. I'll see if it is something I can do as well.

**Comment by PEZ** [comment]
Too low ROI, since it is an involved fix, according to people in the know. Closing this for now.
