### ISSUE TITLE
Incorrect behaviors with shapes wich has been rotated

### ISSUE THREAD

**Issue by mamadaevv** [PEZ/SketchSeparateShapes#3]
![screencast_ 21-56-00 _ 05-02-18 _87dyn](https://user-images.githubusercontent.com/4017693/35823141-8c9fa5d4-0abf-11e8-915f-3b9a56a17086.gif)

**Comment by PEZ** [comment]
Wow. Thanks. Now let's hope I can find a way to fix this.

**Comment by PEZ** [comment]
Should be fixed now. Including any other transform that might be in effect on the shapes. Thanks for the headsup!

**Comment by mamadaevv** [comment]
It's work!
